services:
  wellnest-nginx:
    build:
      context: ./Nginx
      dockerfile: Dockerfile
    container_name: wellnest-nginx
    depends_on:
      - wellnest-user
      - wellnest-prompt
    ports:
      - "8080:8080"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    networks:
      wellnest-network:
        ipv4_address: 172.28.1.10

  wellnest-user:
    build:
      context: ./User-Server
      dockerfile: Dockerfile
    container_name: wellnest-user
    expose:
      - "3000"
    environment:
      - MONGO_URL=mongodb://wellnest-mongodb:27017/wellnest_db
    depends_on:
      - wellnest-mongodb
    networks:
      wellnest-network:
        ipv4_address: 172.28.1.20

  wellnest-prompt:
    build:
      context: ./Prompt-Server
      dockerfile: Dockerfile
    container_name: wellnest-prompt
    expose:
      - "3000"
    environment:
      - MONGO_URL=mongodb://wellnest-mongodb:27017/wellnest_db
    depends_on:
      - wellnest-mongodb
    networks:
      wellnest-network:
        ipv4_address: 172.28.1.30

  wellnest-mongodb:
    image: mongo:6.0
    container_name: wellnest-mongodb
    volumes:
      - wellnest-mongo-data:/data/db
    networks:
      wellnest-network:
        ipv4_address: 172.28.1.101
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      start_period: 5s
      retries: 5

networks:
  wellnest-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

volumes:
  wellnest-mongo-data:

